name: First WF of POC

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "This is first GHA Job"

        - name: Checkout the Repo
          uses: actions/checkout@v4

        - name: List Files
          run: ls -l
          
        - name: Print the Current Working Directory
          run: pwd          
        
        - name: Read the file
          run: cat README.md
